version: '3.4'
services:
  pg_bot_server:
    image: registry2.bale.ai:2443/balepostgres:1.6.0
    container_name: "postgresql"
    restart: always
    environment:
      - POSTGRES_DB=DametGarmLig
      - POSTGRES_PASSWORD=1540487768
      - POSTGRES_USER=muhammad
      - TZ=Asia/Tehran


  app:
    image: "registry2.bale.ai:2443/ligbot:0.0-0"
#    build: .
    hostname: ligbot
    container_name: ligbot
    environment:
      - POSTGRES_DB=
      - POSTGRES_PASSWORD=
      - POSTGRES_USER=
      - BOT_TOKEN=
      - REPORT_DELAY1=
      - REPORT_DELAY2=
      - GROUP_ID=
      - GROUP_ACCESS_HASH=
      - ADMIN_USER_ID=
      - DB_HOST=
    command: python -m Bot.bot
    volumes:
      - .:/ligbot
    depends_on:
      - pg_bot_server


