version: '3.4'
services:
  pg_bot_server:
    image: registry.bale.ai:2443/balepostgres:1.6.0
    container_name: "postgresql"
    restart: always
    environment:
      - POSTGRES_DB=DametGarmLig
      - POSTGRES_PASSWORD=1540487768
      - POSTGRES_USER=muhammad
      - TZ=Asia/Tehran


  app:
    build: .
    hostname: ligbot
    container_name: ligbot
    command: sleep 1h
    volumes:
      - .:/ligbot
    depends_on:
      - pg_bot_server

